### ISSUE TITLE
Already usable?

### ISSUE THREAD

**Issue by nbdy** [mfontanini/pytins#1]
I can't build this with the command 'make'.
Fails at pyicmp.cpp
> check is not a member of Tins::ICMP
> error: no matches converting function ‘gateway’ to type ‘uint32_t (class Tins::ICMP::*)() const {aka unsigned int (class Tins::ICMP::*)() const}’
> - make_setter_wrapper((void (CLASS::*)(ARGTYPE))(&CLASS::NAME))

I receive these errors. Did I miss something?
(Of course I installed libtins inb4)

Would really love to use pytins instead of scapy.

Additional information:
> Parrot 3.6 (Should be debian) 64bit
> gcc 6.3

**Comment by mfontanini** [comment]
pytins is nowhere near being ready/stable. I never finished it, it was just some project I started and got stuck along the way. I'd like to resume its development at some point, but I don't think I have enough free time to work on it.

**Comment by nbdy** [comment]
Too bad. Seems like I gotta code c++.
Thx for the quick answer tho.
